# Generated by Django 4.2.1 on 2023-07-25 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.IntegerField(
                        choices=[(1, "Hacker News"), (2, "Twitter")], default=1
                    ),
                ),
                ("profile_about", models.TextField()),
                ("profile_url", models.TextField()),
                ("comment", models.TextField()),
                ("prompt_response_message", models.TextField(null=True)),
                (
                    "score",
                    models.IntegerField(
                        default=None,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
        ),
    ]
