# Generated by Django 4.2.1 on 2023-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="prompt_response_message",
        ),
        migrations.AddField(
            model_name="lead",
            name="evaluate_response_text",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="prompt_response_text",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="username",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="lead",
            name="comment",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="lead",
            name="profile_about",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="lead",
            name="profile_url",
            field=models.TextField(default=""),
        ),
    ]
