# Generated by Django 4.2.1 on 2023-07-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0009_searchterm_run_status"),
        ("leads", "0003_lead_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="search_term",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="search_terms",
                to="data.searchterm",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["search_term"], name="leads_lead_search__46b309_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["created_at"], name="leads_lead_created_302c6d_idx"
            ),
        ),
    ]
