# Generated by Django 4.2.1 on 2023-07-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0009_searchterm_run_status"),
        (
            "leads",
            "0004_lead_search_term_lead_leads_lead_search__46b309_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="search_term",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="data.searchterm",
            ),
        ),
    ]
