# Generated by Django 4.2.1 on 2023-07-28 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0005_alter_lead_search_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
