# Generated by Django 4.2.1 on 2023-08-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_campaign_unique_campaign_name_per_user"),
        ("leads", "0006_lead_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="campaign",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="campaigns.campaign",
            ),
        ),
    ]
