# Generated by Django 4.2.1 on 2023-08-09 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0007_lead_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="post_score",
            field=models.IntegerField(
                default=1,
                help_text=(
                    "Score the initial post received as to relevancy, on a"
                    " scale of 1-100."
                ),
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="score",
            field=models.IntegerField(
                default=1,
                help_text=(
                    "Score the response received as to relevancy, on a scale"
                    " of 1-100."
                ),
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
