# Generated by Django 4.2.1 on 2023-08-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0008_lead_post_score_alter_lead_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="post_evaluate_response_text",
            field=models.TextField(default="", null=True),
        ),
    ]
