# Generated by Django 4.2.1 on 2023-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0009_lead_post_evaluate_response_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="comment_url",
            field=models.TextField(default=""),
        ),
    ]
