# Generated by Django 4.2 on 2023-05-01 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchterm",
            name="location",
            field=models.IntegerField(
                choices=[(1, "Hacker News"), (2, "Twitter")], default=1
            ),
        ),
        migrations.AddField(
            model_name="searchterm",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_terms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
