# Generated by Django 4.2 on 2023-05-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0003_auto_20230501_1033"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationTemplate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("template", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="prompttemplate",
            name="search_terms",
            field=models.ManyToManyField(
                db_constraint=False, to="data.searchterm"
            ),
        ),
        migrations.AlterField(
            model_name="searchterm",
            name="user",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_terms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PromptResponse",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("response", models.TextField(null=True)),
                ("is_considerable", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_template",
                    models.ForeignKey(
                        db_constraint=False,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="evaluation_template",
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_templates",
                to="data.evaluationtemplate",
            ),
        ),
    ]
