# Generated by Django 4.2.1 on 2023-05-08 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data",
            "0004_evaluationtemplate_alter_prompttemplate_search_terms_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponse",
            name="rating",
            field=models.IntegerField(
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
