# Generated by Django 4.2.1 on 2023-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_promptresponse_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompttemplate",
            name="max_profile_length",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="min_profile_length",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
