# Generated by Django 4.2.1 on 2023-05-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_prompttemplate_max_profile_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompttemplate",
            name="search_terms",
            field=models.ManyToManyField(
                db_constraint=False,
                related_name="prompt_templates",
                to="data.searchterm",
            ),
        ),
    ]
