# Generated by Django 4.2.1 on 2023-05-10 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_alter_prompttemplate_search_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponse",
            name="score",
            field=models.IntegerField(
                default=None,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
