# Generated by Django 4.2.1 on 2023-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0008_promptresponse_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchterm",
            name="run_status",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
