# Generated by Django 4.2.1 on 2023-07-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
        ("data", "0009_searchterm_run_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompttemplate",
            name="campaign",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_templates",
                to="campaigns.campaign",
            ),
        ),
    ]
