# Generated by Django 4.2.1 on 2023-08-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_campaign_name_per_user"
            ),
        ),
    ]
